server:
  port: 0

spring:
  active:
    profile: default
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: 'user-group'
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        acks: all
app:
  kafka:
    producer:
      topic: 'user-topic'
    consumer:
      topic: 'company-topic'
my:
 property:
    test: User service!

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka










